name: Sync src folder to walter-arduino

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  sync-src:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Setup SSH key for deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SRC_REPO_SYNC_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout walter-arduino via SSH
        uses: actions/checkout@v4
        with:
          repository: QuickSpot/walter-arduino
          ssh-key: ${{ secrets.SRC_REPO_SYNC_KEY }}
          path: walter-arduino

      - name: Copy src folder from walter-esp-idf to walter-arduino
        run: |
          rm -rf walter-arduino/src
          cp -R src walter-arduino/src

      - name: Prepare commit info
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_LINK="https://github.com/QuickSpot/walter-esp-idf/pull/${PR_NUMBER}"
          COMMIT_MESSAGE="Sync: src from walter-esp-idf (${PR_LINK})"
          COMMIT_DESCRIPTION="PR title: \"${PR_TITLE}\", nr: ${PR_NUMBER}"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_DESCRIPTION=$COMMIT_DESCRIPTION" >> $GITHUB_ENV


      - name: Commit and push changes in walter-arduino
        run: |
          cd walter-arduino
          git config user.name "src sync action"
          git config user.email "src-sync-action@users.noreply.github.com"
          git add src
          if ! git diff --cached --quiet; then
            git commit -m "${COMMIT_MESSAGE}" -m "${COMMIT_DESCRIPTION}"
            git push origin main
          else
            echo "No changes to sync"
          fi